default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
masto_light: styles/mastodon_light.scss
mastodonte: styles/mastodonte.scss
win95: styles/win95.scss
